In [1]:
import pandas as pd

In [15]:
bank = pd.read_csv("bank/bank/bank-full.csv", sep=';')
credit = pd.read_csv("credit/test_lending_club.csv")
diabetes = pd.read_csv("insurance/car_insurance_claim.csv")
insurance = pd.read_csv("credit/test_lending_club.csv")
mycardial = pd.read_csv("mycardial/data.csv")

In [18]:
mycardial.head(10)

,ID,AGE,SEX,INF_ANAM,STENOK_AN,FK_STENOK,IBS_POST,IBS_NASL,GB,SIM_GIPERT,...,JELUD_TAH,FIBR_JELUD,A_V_BLOK,OTEK_LANC,RAZRIV,DRESSLER,ZSN,REC_IM,P_IM_STEN,LET_IS
0,1,77.0,1,2.0,1.0,1.0,2.0,NaN,3.0,0.0,...,0,0,0,0,0,0,0,0,0,0
1,2,55.0,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
2,3,52.0,1,0.0,0.0,0.0,2.0,NaN,2.0,0.0,...,0,0,0,0,0,0,0,0,0,0
3,4,68.0,0,0.0,0.0,0.0,2.0,NaN,2.0,0.0,...,0,0,0,0,0,0,1,0,0,0
4,5,60.0,1,0.0,0.0,0.0,2.0,NaN,3.0,0.0,...,0,0,0,0,0,0,0,0,0,0
5,6,64.0,1,0.0,1.0,2.0,1.0,NaN,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
6,7,70.0,1,1.0,1.0,2.0,1.0,NaN,2.0,0.0,...,0,0,0,0,0,0,1,0,0,0
7,8,65.0,1,0.0,1.0,1.0,2.0,NaN,2.0,0.0,...,0,0,0,0,0,0,0,0,0,0
8,9,60.0,1,0.0,0.0,0.0,2.0,NaN,2.0,0.0,...,0,0,0,0,0,0,0,0,0,0
9,10,77.0,0,2.0,0.0,0.0,0.0,NaN,3.0,0.0,...,0,0,0,0,0,0,1,0,0,0